import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "./auth/Provider";
import NavBar from "./components/NavBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex-col`}
      >
        <AuthProvider>
          <Theme accentColor="purple" radius="large">
            <NavBar />
            <main className="p-5"> {children}</main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
// TODO LU: I skip 65.10 Configuring Credential provider & 66.11 Registering Users, there are for the user tu register with their own email
